// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw5OLaXUY4zLK-atGkWtEG8dLvQVtYQuI',
    appId: '1:308454467428:web:95865fb56a8349ae623c71',
    messagingSenderId: '308454467428',
    projectId: 'monster-money-manager',
    authDomain: 'monster-money-manager.firebaseapp.com',
    storageBucket: 'monster-money-manager.firebasestorage.app',
    measurementId: 'G-DQ832KJGFX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL-K_pXfRv62qOQpGxMEKmhgkv8kY42ds',
    appId: '1:308454467428:android:481092ae7db97451623c71',
    messagingSenderId: '308454467428',
    projectId: 'monster-money-manager',
    storageBucket: 'monster-money-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVrz69CRHE5-aNASadhrO-j6j3LZscMlc',
    appId: '1:308454467428:ios:7ea211e763bd9509623c71',
    messagingSenderId: '308454467428',
    projectId: 'monster-money-manager',
    storageBucket: 'monster-money-manager.firebasestorage.app',
    iosBundleId: 'com.example.monsterMoneyManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVrz69CRHE5-aNASadhrO-j6j3LZscMlc',
    appId: '1:308454467428:ios:7ea211e763bd9509623c71',
    messagingSenderId: '308454467428',
    projectId: 'monster-money-manager',
    storageBucket: 'monster-money-manager.firebasestorage.app',
    iosBundleId: 'com.example.monsterMoneyManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw5OLaXUY4zLK-atGkWtEG8dLvQVtYQuI',
    appId: '1:308454467428:web:68d8b1afd4f570e8623c71',
    messagingSenderId: '308454467428',
    projectId: 'monster-money-manager',
    authDomain: 'monster-money-manager.firebaseapp.com',
    storageBucket: 'monster-money-manager.firebasestorage.app',
    measurementId: 'G-0FWGB1W0HW',
  );
}
